jira:
  url: https://issues.redhat.com
  project: LPINTEROP
  labels:
    - 4.19-lp
    - 4.20-lp
    - opp-aws-lp
    - rosa-hcp-lp

sippy:
  url: https://sippy.dptools.openshift.org
  releases:
    - "4.19"
    - "4.20"

job_patterns:
  interop:
    - "*interop*"
    - "*opp*"
    - "*lp-*"
  hcp:
    - "*hypershift*"
    - "*rosa-hcp*"
